title: "Sidney Rafilson"
email: "sid.rafilson@nyu.edu"
description: >-
  CV with links to publications, posters, and presentations.
baseurl: "/CV"            # repository name
url: "https://Sid-Rafilson-1617.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Navigation
minima:
  skin: classic
  social_links:
    - { platform: github, user_url: "https://github.com/Sid-Rafilson-1617" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/sid-rafilson" }

# Collections removed; using _data instead for publications and presentations
